import fs from "node:fs";
import path from "node:path";

const root = process.cwd();

const expectedRoutes = [
  "app/page.tsx",
  "app/about/page.tsx",
  "app/academy/page.tsx",
  "app/courses/page.tsx",
  "app/courses/professional-makeup/page.tsx",
  "app/courses/bridal-makeup/page.tsx",
  "app/courses/hair-styling/page.tsx",
  "app/courses/saree-draping/page.tsx",
  "app/courses/masterclasses/page.tsx",
  "app/bridal-studio/page.tsx",
  "app/gallery/page.tsx",
  "app/student-stories/page.tsx",
  "app/testimonials/page.tsx",
  "app/faq/page.tsx",
  "app/contact/page.tsx",
  "app/not-found.tsx",
];

const missing = expectedRoutes.filter((file) => !fs.existsSync(path.join(root, file)));

function collect(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    return entry.isDirectory() ? collect(full) : [full];
  });
}

const sourceFiles = [...collect(path.join(root, "app")), ...collect(path.join(root, "components"))]
  .filter((file) => /\.(tsx?|jsx?)$/.test(file));

const forbidden = [
  /lorem ipsum/i,
  /wired into the production structure/i,
  /final photography/i,
  /will live here/i,
  /placeholder copy/i,
  /generated by ai/i,
];

const copyIssues = [];
for (const file of sourceFiles) {
  const content = fs.readFileSync(file, "utf8");
  for (const pattern of forbidden) {
    if (pattern.test(content)) copyIssues.push(path.relative(root, file) + " matches " + pattern);
  }
}

const internalLinks = new Set();
const linkPattern = /(?:href|to)=["'](\/[^"'?#]*)/g;
for (const file of sourceFiles) {
  const content = fs.readFileSync(file, "utf8");
  let match;
  while ((match = linkPattern.exec(content))) internalLinks.add(match[1]);
}

const knownRoutes = new Set([
  "/",
  "/about",
  "/academy",
  "/courses",
  "/courses/professional-makeup",
  "/courses/bridal-makeup",
  "/courses/hair-styling",
  "/courses/saree-draping",
  "/courses/masterclasses",
  "/bridal-studio",
  "/gallery",
  "/student-stories",
  "/testimonials",
  "/faq",
  "/contact",
]);

const badLinks = [...internalLinks].filter((href) => !knownRoutes.has(href));

if (missing.length || copyIssues.length || badLinks.length) {
  if (missing.length) console.error("Missing routes:\n- " + missing.join("\n- "));
  if (copyIssues.length) console.error("Public copy issues:\n- " + copyIssues.join("\n- "));
  if (badLinks.length) console.error("Unknown internal links:\n- " + badLinks.join("\n- "));
  process.exit(1);
}

console.log("QA audit passed:", expectedRoutes.length, "route files,", sourceFiles.length, "source files,", internalLinks.size, "internal links checked.");
